apiVersion: v1
kind: ConfigMap
metadata:
  name: jjinbbang-admin-server-config
data:
  SPRING_PROFILES_ACTIVE: dev
  AUTHENTIK_ISSUER_URI: https://auth.jjinbbang.kr/application/o/jjinbbang-admin-dev/
  AUTHENTIK_ADMIN_GROUP: jjinbbang-backoffice-admins-dev
  ADMIN_LOGIN_SUCCESS_URI: /
