apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-admin-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-server
    newName: ghcr.io/jjinbbang-web/jjinbbang-server
    digest: sha256:21a8b189ede3cdfa05c495b5e724a2b7dda9d8b0517dacb2e223ac9caaa73d0b
  - name: ghcr.io/jjinbbang-web/jjinbbang-admin
    newName: ghcr.io/jjinbbang-web/jjinbbang-admin
    digest: sha256:0a3d534c3c72f7208ac1373f04c4b7b37b5c46bcce986474a282ab8b41f0eaee
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: web-deployment-patch.yaml
  - path: ingress-patch.yaml
