apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-admin-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-server
    newName: ghcr.io/jjinbbang-web/jjinbbang-server
    digest: sha256:0f83e2b42abf828ef499d1fed30d178747e1f8648ee5301ba57e3db172c44491
  - name: ghcr.io/jjinbbang-web/jjinbbang-admin
    newName: ghcr.io/jjinbbang-web/jjinbbang-admin
    digest: sha256:185b8aef64dce66c19f23b9ec5cc1b7e5c66e906473baed1ed9cf92ca3212b45
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: web-deployment-patch.yaml
  - path: ingress-patch.yaml
