apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-admin-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-server
    newTag: bootstrap
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
