apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-legacy
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-api
    digest: sha256:31b454757c5cd9795d5468b05b172e63358f1b94e1e07b19f7df1595d53594b5
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: delete-ingress.yaml
