apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-legacy
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-api
    digest: sha256:202bb1fe97674e826d7f5837bf5a78dfb74423376481287fba7da23721d8c0b4
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
