apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-legacy
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-api
    digest: sha256:8ddef4b35a547edbce0d5b83a73019777f62bab201ab1001e5c0f38754b4ab58
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: delete-ingress.yaml
