apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-admin
resources:
  - namespace.yaml
  - configmap.yaml
  - server-deployment.yaml
  - server-service.yaml
  - ingress.yaml
  - pdb.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-server
    newTag: bootstrap
