apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jjinbbang-admin
resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
images:
  - name: ghcr.io/jjinbbang-web/jjinbbang-server
    newTag: bootstrap
  - name: ghcr.io/jjinbbang-web/jjinbbang-admin
    newTag: bootstrap
