apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jjinbbang-api-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: jjinbbang-prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JJinBBang-web/jjinbbang-lab.git
    targetRevision: main
    path: apps/jjinbbang-api/overlays/prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
