apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jjinbbang-api-dev.yaml
  - jjinbbang-api-prod.yaml
  - jjinbbang-api-legacy.yaml
  - jjinbbang-admin-dev.yaml
  - jjinbbang-admin.yaml
